language: r
dist: bionic
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

script:
  - sudo apt install -qq gdal-bin gdal-data

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
